#!/bin/bash
# use $1
# db.schools.drop()
# db.users.remove({"type": "manager"})

mongo <<EOF
use node
db.absences.drop()
db.coursenames.drop()
db.courses.drop()
db.schedules.drop()
db.groups.drop()
db.sessions.drop()
db.subjectnames.drop()
db.subjects.drop()
db.tokens.drop()
db.users.remove({"type": "professor"})
db.users.remove({"type": "student"})
quit()
exit
EOF
